gwas/gwas.py
By adding hashbang as the first line of gwas.py it can be executed by running
`./gwas.py` instead of `python ./gwas.py`.
Note that my editor removes trailing whitespace, that's why the diff
shows a lot of changes that doesn't seem to do anything.
=> Makes gwas.py an executable

usecases/gwas_demo.md
Changes the relative link to `sumstats_specification.md` to be based on the parent directory instead of the current directory (which gave you a `404 Not found` before).
=> Fixes broken link to sumstats_specification.md

gwas/gwas.py
When using the default value of the gwas.py flag `vcf-field` the final flag output to SAIGE will be formatted as:
```
--vcfField=['DS']
```
This commit fixes this, so that the final flag instead will be output as:
```
--vcfField=DS
```
=> Fixes incorrect `--vcfField` format

gwas/gwas.py
Makes sure `--config` is passed on to `gwas.py` commands
=> Resolves #34

.github/workflows/docker.yml, .github/workflows/greetings.yml, .github/workflows/python.yml, .github/workflows/stale.yml, CHANGELOG.md, src/dockerfiles/python3/Dockerfile, tests/test_python3.py
Fixes #44
- Adds some basic GitHub actions from https://github.com/precimed/container_template.git
- Added python test loading explicitly installed packages
=> GH actions (docker&python lint, greetings, stale)

CHANGELOG.md, docs/r.md, singularity/enigma-cnv.sif, singularity/ipsychcnv.sif, singularity/tryggve_query.sif
Fixes #58 
- enigma-cnv.sif and ipsychcnv.sif is moved to https://github.com/comorment/iPsychCNV
enigma-cnv.sif is also available here: in https://github.com/ENIGMA-git/ENIGMA-CNV/tree/main/CNVCalling/containers
- tryggve_query.sif  is moved to https://github.com/comorment/Tryggve_psych
- remove LAVA-related lines in ``docs/r.md``  (those lines were already included in https://github.com/comorment/magma/blob/main/README.md )
=> Move out enigma-cnv.sif , ipsychcnv.sif, tryggve_query.sif 

gwas/gwas.py, usecases/gwas_real/combine_figures.py
=> Reformat gwas.py and combine_figures.py 

CHANGELOG.md, usecases/LDpred2/README.md, usecases/LDpred2/complementSumstats.R, usecases/LDpred2/fun.R, usecases/LDpred2_test/scripts/sumstats.sh, usecases/LDpred2_test/unittest/fun.R
Fixes #157
- Made `complementSumstats.R` script write output to file by default.
- The default chromosome # output column is `CHR` (renamed from `#CHROM`)
- Added test of `rename_column` function in `fun.R` script.
=> Make `complementSumstats.R` write file output by default

usecases/LDpred2/ldpred2.R
Minifix. The .bk backing file which must exist in parallel to the .rds file as created by the `createBackingFile.R` script is not explicitly referenced.
- Clarify `--geno-file-rds` arg by referencing the .bk file.
=> clarify `--geno-file-rds` arg

CHANGELOG.md, scripts/pgs/LDpred2/ldpred2.R, tests/test_LDpred2/scripts/extended.sh, version/version.py
Fixes #179 
- Adds test and fix of LDpred2 crash occurring if sumstats column header is uppercase (e.g., `CHR`), and column also encodes chromosomes using characters (e.g., `X`)
=> Fix LDpred2 error with uppercase chromosome column header

CHANGELOG.md, scripts/pgs/LDpred2/README.md, version/version.py
Fixes #190  
- Added info on invoking R argparser help output for LDpred2 scripts
=> Info on `ldpred2.R  --help` functionality

CHANGELOG.md, scripts/pgs/LDpred2/ldpred2.R, tests/test_LDpred2/scripts/extended.sh, version/version.py
Fixes #191
- Ignore LDpred2 `--col-bp <arg>` in case `--merge-by-rsid` is used
- `--merge-by-rsid` defaults to `TRUE` if used, otherwise `FALSE`
=> LDpred2.R: if `--merge-by-rsid` is used, ignore `--col-bp <arg>`

CHANGELOG.md, scripts/pgs/LDpred2/README.md, scripts/pgs/LDpred2/ldpred2.R, version/version.py
Fixes #189
- Added `--genomic-build hg18/hg19/hg38` option to `ldpred2.R` in order to use correct `pos` column in `ldpred2_ref/map_hm3_plus.rds` file in case geno/sumstat files uses another build. 
- Added some explanation of the feature in the LDpred2 README file
=> LDpred2: Build 37/38 behavior/documentation

CHANGELOG.md, scripts/pgs/LDpred2/README.md, scripts/pgs/LDpred2/ldpred2.R, version/version.py
Fixes #203
- Add an option to redirect temporary data for `LDpred2.R` using `--tmp-dir` flag. By default using R's`base::tempdir()`
=> `LDpred2.R`: redirect temporary data during runs

CHANGELOG.md, scripts/pgs/LDpred2/ldpred2.R, version/version.py
Fixes #223
- Fixed parsing of arguments to `--genomic-build` in `ldpred2.R`
=> `ldpred2.R`: fix `hg_38` should be `hg38` and `hg_18` should be `hg18`

CHANGELOG.md, scripts/gwas/gwas.py, version/version.py
Fixes #230, #232 
-Renamed Plink2 case/control GWAS output files to `*.logistic` (from `*.firth` and `*.logistic.hybrid`)
-Added `--firth` option to `gwas.py` 
=> `gwas.py`: fixed gwas demo run and IID column position

CHANGELOG.md, scripts/gwas/config.yaml, scripts/gwas/gwas.py
Fixes #245 
- The dictionaries regenie:step1, regenie:step2 and plink2 in `config.yaml` are now used to pass commands created by `gwas.py`. For example, the snippet below can be added to the `config.yaml` file to include the `--force-step1` option in the step 1 of the `regenie` analysis.
```
regenie:
step1:
force-step1:
```
=> add support for additional options in gwas.py

CHANGELOG.md, docker/dockerfiles/python3/Dockerfile, tests/test_python3.py
Fixes #273
- Adds requested Python packages + PRSice_linux binary
=> `python3`: add missing packages

.github/workflows/docker_build_gwas.yml, .github/workflows/docker_build_hello.yml, .github/workflows/docker_build_push_gwas.yml, .github/workflows/docker_build_push_hello.yml, .github/workflows/docker_build_push_python3.yml, .github/workflows/docker_build_push_r.yml, .github/workflows/docker_build_python3.yml, .github/workflows/docker_build_r.yml, CHANGELOG.md, docker/scripts/R/github.R, docker/scripts/apt_get_essential.sh, docker/scripts/install_bcftools.sh, docker/scripts/install_ldak.sh, docker/scripts/install_minimac4.sh, docker/scripts/install_regenie.sh, docs/singularity/gwas.md, test-requirements.txt, tests/test_gwas.py, tests/test_hello.py, tests/test_python3.py, tests/test_r.py
Fixes #276 
- Runs unit tests as part of the container build procedure
=> Run unit tests during Docker build procedure

.github/workflows/docker_build_push_gwas.yml, .github/workflows/docker_build_push_hello.yml, .github/workflows/docker_build_push_python3.yml, .github/workflows/docker_build_push_r.yml, CHANGELOG.md
Fixes #290
- Add ORAS to build-push runner env
=> Build-push actions fail: `oras: not found`

CHANGELOG.md, docker/dockerfiles/python3/Dockerfile, docker/scripts/apt_get_essential.sh, tests/test_python3.py, version/version.py
Fixes #302 
- adds plink2 binary, and dask, pyarrow, fastparquet to python3.sif build
- bumps version to 1.9.1 (new release)
=> `python3.sif`: containerize tools
