comorment/containers

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation-issue.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- CONTRIBUTING.md
Closes #47. Also adds a `CONTRIBUTING.md` file with some instructions at the top level.
> Add issue/PR templates

- .gitignore
- CHANGELOG.md
- docs/hello.md
- src/README.md
- src/dockerfiles/gwas/Dockerfile
- src/scripts/install_shapeit4.sh
- tests/test_gwas.py
Fixes #50
- adding Shapeit4 and its dependency HTSlib to future `gwas.sif` builds
- adds a simple test of the included `shapeit4.2` binary
> Add Shapeit4 (and dependency HTSlib) to gwas.sif

- usecases/README.md
Fixes #81
MiXeR usage is now covered in a separate github repo (https://github.com/comorment/mixer) 
> Remove broken links to MiXeR usage scenarios

- CHANGELOG.md
- tests/extras/GlucoseExample.tar.gz
- tests/test_gwas.py
Fixes #83
- Add tests for `metal`, `qctool` in`gwas.sif`.
> Add tests for `metal`, `qctool` in`gwas.sif`.

- CHANGELOG.md
- reference/README.md
- singularity/ldsc.sif
Fixes #56 . The changes were meant to be in PR #86 , but I forgot to push them.
- update CHANGELOG.md and remove the actual ldsc.sif file.
> Remove ldsc.sif file

- src/README.md
- src/dockerfiles/gwas/Dockerfile
- src/scripts/install_bcftools.sh
- src/scripts/install_htslib.sh
- src/scripts/install_king.sh
- src/scripts/install_metal.sh
- src/scripts/install_shapeit4.sh
- src/scripts/patches/shapeit4.makefile.diff
Fixes #78
- install ``HTSlib-v1.12`` to ``/usr/`` for building ``shapeit4`` and ``bcftools``
- clean up ``king`` install script/gwas-test
> clean up install of htslib, bcftools, shapeit4

- tests/ldpred2/build.sh
- tests/ldpred2/container.def
- tests/ldpred2/impute.R
- tests/ldpred2/ldpred2.R
- tests/ldpred2/run_ldpred2.sh
As discussed in this [thread](https://github.com/comorment/containers/pull/91), we'll merge these new files via that PR into the main branch.
> LDPRED2 scripts for PRS analyses

- CHANGELOG.md
- README.md
- citation.cff
Fixes #102
- add status badges (DOI, readthedocs, GH actions)
> add citation.cff and badges

- usecases/LDpred2/ldpred2.R
- fix the way [number](https://www.rdocumentation.org/packages/bigstatsr/versions/0.9.1/topics/nb_cores) of cores for LDpred2 is set
> set appropriate number of CPU cores

- docs/README.md
There's no issue created.
- minor correction to docs
> Remove reference to `ldsc.sif` (moved)

- CHANGELOG.md
- gwas/gwas.py
- tests/test_gwas_py.py
Fixes #32 
- `gwas.py --variance-standardize` option now throws an error when applied to columns with no variance
- added a test for `variance-standardize` option.
> --variance-standardize for columns without variation

- gwas/gwas.py
- gwas/pheno_geno_specification.md
- tests/test_gwas_py.py
> Allow custom name for IID columns 

- .github/workflows/docker.yml
- .github/workflows/python.yml
- CHANGELOG.md
- gwas/gwas.py
Fixes #125 
- `flake8` should complain for line lengths > 120 chars (E501)
- `flake8` should ignore number of newlines between functions altogether (E302)
> update config for flake8 linter

- CHANGELOG.md
- usecases/LDpred2/README.md
- usecases/LDpred2/calculateLD.R
- usecases/LDpred2/ldpred2.R
- usecases/LDpred2/run_ldpred2_slurm.job
- usecases/LDpred2_example/README.md
- usecases/LDpred2_example/data/ld/README
- usecases/LDpred2_example/run.sh
Fixes #108 
This adds a new script `calculateLD.R` using the R-packaged bigSNPR to estimate LD.
- Takes a bigSNPR genotype (.rds) file as input
- Filter SNPs to use when calculating LD by a list of SNPs or a sumstat file.
- Optional random sampling of individuals to use in estimation.
- Outputs one table ("map") with SNP LD and a correlation matrix for each chromosome (.rds) to use as input in `LDpred2.R`.
- Renamed flag `--geno-file` to `--geno-file-rds` in `LDpred2.R`
So far I've only tested this using the simulated data provided by the LDpred2 tutorial. The ldsc regression gives a slightly different estimate than the tutorial; `Intercept = 0.9502722 H2 = 0.3002906` versus tutorial `## 0.9496371 0.2981213`. Maybe something with the filtering …
> LD-estimation for LDpred2 using bigSNPR

- tests/test_gwas.py
Fixes #135
- Change `--home` from `/tmp` to temporary directory in `test_gwas_king`
> change home to temporary folder in test_gwas_king

- usecases/LDpred2/README.md
- usecases/LDpred2/imputeGenotypes.R
- usecases/LDpred2_example/run.sh
Fixes some minor issues in #131
> some minor fixes to LDpred2 imputation

- CHANGELOG.md
- usecases/LDpred2/complementSumstats.R
Fixes #155
- Fixed crash in `complementSumstats.R` script
> fixed print statements

- usecases/LDpred2_test/scripts/sumstats.sh
Just a fix of a test script in PR #159 
> Reorganized test run

- CHANGELOG.md
- RELEASES.md
Fixes #168 
- Added RELEASES.md document explaining steps to make releases.
> Add RELEASES.md file

- CHANGELOG.md
- version/version.py
- bumb version and updated CHANGELOG for v1.2 release.
> Prep release v1.2

- CHANGELOG.md
- reset CHANGELOG.md for future releases. This will be released as feature/bugfix release 1.3.0
> prep 1.3.0 release

- RELEASES.md
Fixes #174
- Briefly document that one should sync code to TSD p697. Should the details from https://github.com/comorment/containers/issues/174 be included in RELEASES.md ?
> Fix #174 - sync releases to TSD

- CHANGELOG.md
- scripts/pgs/LDpred2/createBackingFile.R
- tests/test_LDpred2/run.sh
- tests/test_LDpred2/scripts/backingfile.sh
- version/version.py
Fixes #199 
- Added a feature to ``<LDpred2>/createBackingFile.R`` to convert .bgen files + test script update 
> `LDpred2/createBackingFile.R`: process .bgen files

- .readthedocs.yml
- CHANGELOG.md
- sphinx-docs/source/environment.yml
- version/version.py
Fixes #207
- Fix broken documentation build on ReadTheDocs
> Docs builds are failing on readthedocs.io

- CHANGELOG.md
- docker/README.md
- docker/dockerfiles/gwas/Dockerfile
- docker/scripts/apt_get_essential.sh
- docker/scripts/install_bcftools.sh
- docker/scripts/install_htslib.sh
- docker/scripts/install_ldak.sh
- docker/scripts/install_metal.sh
- docker/scripts/install_minimac4.sh
- docker/scripts/install_qctools.sh
- docker/scripts/install_snptest.sh
- singularity/gwas.sif
- tests/test_gwas.py
Fixes #213 
Fixes #212 
Fixes #211 
Fixes #209
Fixes #205 
- Adds GNU debugger (gdb), SNPTEST and LDAK
- Updates qctool, METAL
- Rebuilt gwas.sif
- Updated tests
> Add/update requested gwas.sif binaries

- CHANGELOG.md
- docker/README.md
- docker/dockerfiles/r/Dockerfile
- docker/scripts/R/github.R
- docker/scripts/build_docker.sh
- singularity/r.sif
- tests/extras/r.R
- version/version.py
Fixes #220 
- Adding CC-GWAS R package to `r.sif`
- Updates packaged binaries `gcta64` (v1.94.1) and `PRSice_linux` (v2.3.5) matching that of `gwas.sif`
- fixed `build_docker.sh` script
> `r.sif`: Add CC-GWAS R package

- .github/pull_request_template.md
- CHANGELOG.md
- README.md
- RELEASES.md
- docs/singularity/gwas.md
- docs/singularity/hello.md
- sphinx-docs/source/conf.py
- sphinx-docs/source/index.rst
- sphinx-docs/source/singularity/README.md
- sphinx-docs/source/singularity/external.md
Fixes #235
- minor adjustment to docs
- added citations/urls to code for tools in gwas.sif and hello.sif
- removed reference to "writing docstrings"
> Documentation updates

- CHANGELOG.md
- docs/singularity/python3.md
- docs/singularity/r.md
- Add some references to containerized software tables
> references

- CHANGELOG.md
- README.md
- citation.cff
- add citation info to main README
> citation stuff

- CHANGELOG.md
- scripts/gwas/gwas.py
Fixes #237 
Added the options `--extract`, `--extract-step1`, `--extract-step2`, `--exclude`, `--exclude-step1` and `--exclude-step2` options to `gwas.py`
> add --extract and --exclude options to filter snps in gwas.py

- CHANGELOG.md
- docs/singularity/r.md
Fixes #247
- Add some info on invoking Rstudio-server with `r.sif` + R package details.
> `r.sif`: Rstudio-server docs

- .github/workflows/docker_build_push.yml
- CHANGELOG.md
- docker/scripts/apt_get_essential.sh
- push `hello` container image to GitHub container registry from main branch. 
> Build container image `hello:latest` using build action 

- .github/workflows/docker_build_gwas.yml
- .github/workflows/docker_build_hello.yml
- .github/workflows/docker_build_push_gwas.yml
- .github/workflows/docker_build_push_hello.yml
- .github/workflows/docker_build_push_python3.yml
- .github/workflows/docker_build_push_r.yml
- .github/workflows/docker_build_python3.yml
- .github/workflows/docker_build_r.yml
- CHANGELOG.md
- INSTALL.md
- README.md
- docker/dockerfiles/gwas/Dockerfile
- docker/dockerfiles/hello/Dockerfile
- docker/dockerfiles/python3/Dockerfile
- docker/dockerfiles/r/Dockerfile
- docker/scripts/R/github.R
- docker/scripts/apt_get_essential.sh
- docker/scripts/install_bcftools.sh
- docker/scripts/install_htslib.sh
- docker/scripts/install_king.sh
Fixes #256 
- Adding GH actions to:
- build Docker images (on every PR to main branch/main branch edit)
- build and push Docker and Singularity images to GHCR.io on every new version tag.
- some updates to INSTALL.md reflecting the above
- revised installer scripts, bumped package versions
> Add container build/push actions

- .github/workflows/docker_build_gwas.yml
- .github/workflows/docker_build_hello.yml
- .github/workflows/docker_build_push_gwas.yml
- .github/workflows/docker_build_push_hello.yml
- .github/workflows/docker_build_push_python3.yml
- .github/workflows/docker_build_push_r.yml
- .github/workflows/docker_build_python3.yml
- .github/workflows/docker_build_r.yml
Fixes #261
- Fixed wrong Docker build target on ghcr.io
> Fixed wrong Docker build target

- .github/workflows/docker_build_push_r.yml
Fixes #263
- use "comorment/r" as search string for replacing with "comorment/r_sif" in push tags
> search and replace `r` fix

- docker/scripts/R/github.R
> Update gSEM Git SHA

- docker/scripts/apt_get_essential.sh
> bump wget version

- docker/scripts/install_ldak.sh
Fixes #271
- Fix path to ldak binary
> buggered ldak download

- .github/workflows/docker_build_push_gwas.yml
- .github/workflows/docker_build_push_hello.yml
- .github/workflows/docker_build_push_python3.yml
- .github/workflows/docker_build_push_r.yml
Fixes #278 
- Fix missing git-lfs in test step 
> Fix broken build-push action

- docker/scripts/install_qctools.sh
- bump fossil version for qctools install
> bump fossil version

- CHANGELOG.md
- docker/dockerfiles/r/Dockerfile
- docker/scripts/R/bioconductor.R
- docker/scripts/R/cran.R
- docker/scripts/R/github.R
- docker/scripts/apt_get_essential.sh
- docker/scripts/install_bcftools.sh
- docker/scripts/install_minimac4.sh
- tests/extras/r.R
Fixes #285
Fixes #286
- Adds R packages AER, MendelianRandomization, gwasurvivr
- Pull rocker/verse image from ghcr.io
- use posit/bioconda packages from 2024.09.04 (from 2024.09.01)
> Containerize missing tools/update

- CHANGELOG.md
- update changelog for 1.9.0 release
> updated changelog for 1.9.0
